
export interface GalleryModalImage {
    src : string,
    width : number,
    height : number,
    title : string,
    description : string
}

export const imageList : GalleryModalImage[] = [
    { src: '/art/art-3.webp', width : 827,  height : 1060, title : 'title 3', description : 'description 3 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
    { src: '/art/art-1.webp', width : 800,  height : 1236, title : 'title 1', description : 'description 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
    { src: '/art/art-2.webp', width : 800,  height : 800,  title : 'title 2', description : 'description 2 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
    { src: '/art/art-3.webp', width : 827,  height : 1060, title : 'title 3', description : 'description 3 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
    { src: '/art/art-4.webp', width : 1006, height : 1007, title : 'title 4', description : 'description 4 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
    { src: '/art/art-1.webp', width : 800,  height : 1236, title : 'title 1', description : 'description 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
    { src: '/art/art-2.webp', width : 800,  height : 800,  title : 'title 2', description : 'description 2 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
    { src: '/art/art-4.webp', width : 1006, height : 1007, title : 'title 4', description : 'description 4 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
    { src: '/art/art-1.webp', width : 800,  height : 1236, title : 'title 1', description : 'description 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
    { src: '/art/art-2.webp', width : 800,  height : 800,  title : 'title 2', description : 'description 2 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
    { src: '/art/art-3.webp', width : 827,  height : 1060, title : 'title 3', description : 'description 3 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
    { src: '/art/art-1.webp', width : 800,  height : 1236, title : 'title 1', description : 'description 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?Laudantium alias blanditiis nemo voluptatem dolor, ad facilis ipsam debitis modi velit?' },
]
